### ISSUE TITLE
Unicode error on French language (don't know how fix it)

### ISSUE THREAD

**Issue by x9nico** [DragonetMC/DragonProxy-Translations#20]
Hi, in my logs, got this characters : 
![image](https://user-images.githubusercontent.com/8091015/34619052-1ce53948-f241-11e7-87c6-b0ac6f619ab5.png)
It is show like that when a sentence has that: é, è etc.
Possible to fix that please ? :)

**Comment by DefinitlyEvil** [comment]
convert them to `\uXXXX` format

**Comment by x9nico** [comment]
And how can we know what is the number of \uXXX ?

**Comment by HoverEpic** [comment]
It's probably the file format non UTF-8, or the file reader. It's a minor bug. Thanks for reporting.

**Comment by HoverEpic** [comment]
And the "Création de la discussion pool..." is not french at all =P, should be "Création des unités de traitements (Nombre : 16)" ^^

**Comment by HoverEpic** [comment]
Could try to convert to UTF-8 without bom for testing, should works.

**Comment by DefinitlyEvil** [comment]
It has nothing to do with UTF-8, same in Bukkut... It must use Unicode alternative...

**Comment by HoverEpic** [comment]
Got things like this working multiple times, it's possible. I will try.

**Comment by x9nico** [comment]
I tested all UTF-8 it is not work

**Comment by HoverEpic** [comment]
Fixed in https://github.com/DragonetMC/DragonProxy/commit/bbe6a3559a7cf920aa07132de4140fc00bf5ce92
