### ISSUE TITLE
IMPORTANT ISSUE - I don't have access xD

### ISSUE THREAD

**Issue by TheDiamondYT1** [DragonetMC/DragonProxy-Translations#7]
Admin or owner access please @DefinitlyEvil

**Comment by TheDiamondYT1** [comment]
To the org

**Comment by DefinitlyEvil** [comment]
Yes.

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil Why not to the whole organization :(

@jlirochon has it

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Yes the whole org added, by default only admin group can access all repos. You are in `Developers` group so we have to add manually. xD

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil I can't invite anybody or create repos -_-

There should be an option in the "Members" tab to give me admin access. Idk i may be confusing it with Owner

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Admin=Owner so I think it is not necessary to give all members admin access right?

**Comment by TheDiamondYT1** [comment]
@DefinitlyEvil  No but its neccercary to give me owner :P

**Comment by DefinitlyEvil** [comment]
@RandomAltThingy Okay, I will consider about this. ;P

**Comment by TheDiamondYT1** [comment]
"Consider"

:cry:

**Comment by jlirochon** [comment]
Hi @RandomAltThingy, why do you need it ?
